# Generated by Django 3.2.6 on 2021-08-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
